name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  node-version: '16'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}
      - name: Install dependencies
        run: npm ci
      - run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}
      - name: Cache outputs
        id: outputs-cache
        uses: actions/cache@v2
        with:
          path: |
            *.js
            src/**/*.js
            test/**/*.js
          key: ${{ runner.os }}-node-${{ hashFiles('*.ts', 'src/**/*.ts', 'test/**/*.ts') }}
      - name: Install dependencies
        run: npm ci
      - name: Install Typescript
        if: steps.outputs-cache.outputs.cache-hit != 'true'
        run: npm install -g typescript
      - if: steps.outputs-cache.outputs.cache-hit != 'true'
        run: npm run build
    needs: lint
  deploy:
    if: github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Cache outputs
        uses: actions/cache@v2
        with:
          path: |
            *.js
            src/**/*.js
            test/**/*.js
          key: ${{ runner.os }}-node-${{ hashFiles('*.ts', 'src/**/*.ts', 'test/**/*.ts') }}
      - name: Install dependencies
        run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    needs: build
